### Read all users
GET http://localhost:4000/user-api/users

### Read a user by ObjectID
GET http://localhost:4000/user-api/users/697dbcb6e26f7ce2e0286a04


### Create a new user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username": "arun",
    "password": "bandra",
    "age": 20
}


### Update a user
PUT http://localhost:4000/user-api/users/697e0b636f969cb2d1e40f96
Content-Type: application/json

{
    "username": "arun",
    "password": "bandra",
    "age": 23
}

### Delete a user by ObjectID
DELETE http://localhost:4000/user-api/users/697e0b636f969cb2d1e40f96


### Read product
GET http://localhost:4000/product-api/products

### Read product by id 
GET http://localhost:4000/product-api/products/697e15596f969cb2d1e40fbc

###Create a new product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid": 101,
    "productName": "laptop",
    "price": 50000
}

### Update a product
PUT http://localhost:4000/product-api/products/697e15596f969cb2d1e40fbc
Content-Type: application/json

{
    "pid": 101,
    "productName": "laptop",
    "price": 45000
}

### Delete a product by id
DELETE http://localhost:4000/product-api/products/697e15596f969cb2d1e40fbc